server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mydatabase?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: lzh123456

jwt:
  secret: mysecret
  expiration: 1296000
  tokenStart: "Bearer "
  tokenName: Authorization
  defaultPassword: "123456"

#mybatis
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.swpu.uchain.community.entity
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

